  
version: '2'

services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
        - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
    volumes:
        - mongo:/var/lib/mongo/data

volumes:
  mongo: